// SPDX-License-Identifier: GPL-2.0+
/*
 * Copyright (c) 2026 Roman Vivchar <rva333@protonmail.com>
 */

#ifndef _DT_BINDINGS_MEMORY_MT6572_MEMORY_PORT_H_
#define _DT_BINDINGS_MEMORY_MT6572_MEMORY_PORT_H_

#define M4U_PORT_DISP_OVL		0
#define M4U_PORT_DISP_RDMA		1
#define M4U_PORT_DISP_WDMA		2
#define M4U_PORT_DISP_DBI		3
#define M4U_PORT_CAM_WDMA		4
#define M4U_PORT_CMDQ			5
#define M4U_PORT_VENC_BSDMA_VDEC_POST0	5
#define M4U_PORT_MDP_RDMA		7
#define M4U_PORT_MDP_WDMA		8
#define M4U_PORT_MDP_ROTO		9
#define M4U_PORT_MDP_ROTCO		10
#define M4U_PORT_MDP_ROTVO		11
#define M4U_PORT_VENC_MVQP		12
#define M4U_PORT_VENC_MC		13
#define M4U_PORT_VENC_CDMA_VDEC_CDMA	14
#define M4U_PORT_VENC_REC_VDEC_WDMA	15

#endif
